name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  psalm:
    name: Run Psalm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0"
          - "8.1"
          - "8.2"
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:2.1

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.composer/cache
            vendor
          key: php-${{ matrix.php-version }}
          restore-keys: php-${{ matrix.php-version }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Psalm
        run: composer psalm -- --php-version=${{ matrix.php-version }} --shepherd

  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0"
          - "8.1"
          - "8.2"
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:2.1

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.composer/cache
            vendor
          key: php-${{ matrix.php-version }}
          restore-keys: php-${{ matrix.php-version }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit
        run: composer phpunit
        env:
          OPENSTACK_AUTH_URL: ${{ secrets.OPENSTACK_AUTH_URL }}
          OPENSTACK_REGION: ${{ secrets.OPENSTACK_REGION }}
          OPENSTACK_USERNAME: ${{ secrets.OPENSTACK_USERNAME }}
          OPENSTACK_PASSWORD: ${{ secrets.OPENSTACK_PASSWORD }}
          OPENSTACK_PROJECT_ID: ${{ secrets.OPENSTACK_PROJECT_ID }}
          OPENSTACK_CONTAINER_NAME_PREFIX: ${{ secrets.OPENSTACK_CONTAINER_NAME_PREFIX }}
